### ISSUE TITLE
Quest tracker overlapping minimap

### ISSUE THREAD

**Issue by mikaile676** [GoldpawsStuff/AzeriteUI#139]
### Make sure you can check all these boxes  

- [X] I have the latest addon version available from CurseForge.
- [X] I restarted the entire game after updating the addon, not just relogged or reloaded. (Only needed in Classic.)

### What game version(s) does it happen in? Choose your version and the highest expansion you own. 

- Live Realms
	- [ ] Classic Era 
	- [X] Burning Crusade Classic 
	- [ ] Shadowlands 
- Public Test Realm 
	- [ ] Classic Era 
	- [ ] Burning Crusade Classic 
	- [ ] Shadowlands 

### What addon theme(s) does it happen in?  

- [ ] Azerite 
- [X] Legacy 
- [ ] I don't know what this means. 

### Does this happen with ONLY this addon enabled?  

- [X] Yes 
- [ ] No 

### Does this happen with absolutely all addons (this included) disabled?  

- [ ] Yes 
- [X] No 

### What classes does it happen on?  

- [ ] Death Knight 
- [ ] Demon Hunter 
- [ ] Druid 
- [X] Hunter 
- [ ] Mage 
- [ ] Monk 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior
